### ISSUE TITLE
关于更新内容的模式建议

### ISSUE THREAD

**Issue by tarscoding** [phodal/growth-ionic#11]
如果开发组成员来更新审核内容显然更新不会很快,内容不会很多,所以采用"维基模式"也许是一个可行的方案

任何人都可以编辑更新"Growth"这个知识库或者说学习路径指导库

同时不是每个人需要所有的内容(当然追求全栈工程师的除外),所以可以一键切换出私人版本的"Growth",
这里面只有用户自己的成长数据,以及自己刚兴趣的内容

**Comment by zuomoumou666** [comment]
请问一下，cordova-plugin-code-push，是否能越过APP store的审核。更新JS文件

**Comment by phodal** [comment]
可以的

**Comment by phodal** [comment]
Done:

https://github.com/phodal/awesome-growth
https://github.com/phodal/awesome-practise-project
https://github.com/phodal/articles
