### ISSUE TITLE
【用户需求征集】

### ISSUE THREAD

**Issue by phodal** [phodal/growth-ionic#13]
在这里写下你想要学习的内容、技术栈、学习曲线等等。

**Comment by 1866** [comment]
AngularJS ~

**Comment by dusdong** [comment]
Electron，最好能用Electron做个开源的桌面app，呵呵

**Comment by phodal** [comment]
@dusdong Electron构建出来的桌面应用太大了。

**Comment by dusdong** [comment]
1、目前看来，Electron应该是Html5桌面应用的未来。
2、对于ionic的应用，应该可以直接在Electron下运行吧，迁移成本不高。
3、目前没有Electron甚至没有一个专门的中文社区，资料很少。
4、没有一个标杆的中文开源Electron应用。

**Comment by phodal** [comment]
@dusdong OK 已经加到Roadmap里了

**Comment by dusdong** [comment]
OK~ 万分期待！

**Comment by phodal** [comment]
@dusdong 你用的电脑是Mac OS or Windows or Linux，已经可以用桌面版了 。

**Comment by dusdong** [comment]
太棒了，我已经在windows上跑起来了。一套代码，三屏运行！
目前发现的问题：
1、内容为一张图片的页面，图片会被拉伸的很难看，如：我的技能图谱。
2、打开新页面时，页面指引也很混乱。
3、解决方案的内容页点不开。

**Comment by phodal** [comment]
@dusdong 单独建个另外的issue吧~~
