### ISSUE TITLE
Growth 1.0 开发路线图

### ISSUE THREAD

**Issue by phodal** [phodal/growth-ionic#15]
:smile::smile::smile:

这是一份 Growth 1.0 的开发路线，包括：
- 以后可能会更改的计划或待办事项
- 有其它功能需求吗？
## Done
- [x] 版本
  - [x] WP版
  - [x] Android版
  - [x] Web版
  - [x] Electron 桌面版 #13 
- [x] 解决方案
- [x] 技能测验
  - [x] 问题收集和展示 
- [x] Web七日谈
  - [x] Todo事项
  - [x] 书单推荐
  - [x] 文章列表
  - [x] 工具推荐
- [x] 技能树
  - [x] GET技能
  - [x] 生成技能树
  - [x] 意见和建议
  - [x] 成就系统
- [x] 社区
  - [x] 创建社区
  - [x] 用户登录
  - [x] 用户分享 
  - [x] 回帖@功能

**Comment by JimmyLv** [comment]
可以增加对每部分内容的评论功能么？

**Comment by phodal** [comment]
@JimmyLv 之前想过这个功能哈，但是后来想了想，就拆分开了：
1. 做到社区里面
2. 文章部分可以直接打开编辑
