### ISSUE TITLE
Growth 3.0 开发设想

### ISSUE THREAD

**Issue by phodal** [phodal/growth-ionic#19]
:smile::smile::smile:

这是一份 Growth 未来的发展路线，包括：
- 以后可能会更改的计划或待办事项
- 有其它功能需求吗？

**Comment by phodal** [comment]
![demo](https://cloud.githubusercontent.com/assets/472311/21293656/2f643136-c566-11e6-8429-d704de90d157.jpg)

**Comment by phodal** [comment]
![demo2](https://cloud.githubusercontent.com/assets/472311/21294071/f517aad0-c56f-11e6-9f8a-f191453a03e2.jpg)

**Comment by dusdong** [comment]
楼主，3.0选用的技术栈有哪些？

**Comment by phodal** [comment]
move to https://github.com/phodal/growth
