### ISSUE TITLE
为什么不在 release 中发布版本呢？

### ISSUE THREAD

**Issue by dusdong** [phodal/growth-ionic#25]
只有一个0.8.10，现在是不是已经1.0.0了呢？如果能在 release 中发布出来就就好了，这样一方面我们可以看到growth的进步，另一方面方便查看代码。谢谢

**Comment by phodal** [comment]
@dusdong 好的哈~。不过，用Git的历史更容易看到变化。。下次，再一个大版本发布一次。。

并且0.8.10是比较稳定的版本，1.0.0是只有iOS的才是。

**Comment by dusdong** [comment]
好的，了解了
