### ISSUE TITLE
我遇到的ionic的一些坑

### ISSUE THREAD

**Issue by sunbirds** [phodal/growth-ionic#3]
ionic 确实是一个便捷快速的web app开发框架，这些是我两三个月前遇到没有很好解决的问题，不知道ionic现在解决好了没有。

我觉得最严重的一个问题就是android 不流畅。当你在一个view里，有过多的元素的时候，即使使用ionic提供的collection-repeat也不回很smooth，用crosswalk打包后会好一点。但是同时app 会变大很多。我研究过crosswalk框架，之所以会比app 会变大，是因为crosswalk自己视线很xwalkwebview（相比android的webview）一级其他的一些view和function。

然后，像phodal这种app，从文章列表到详情，应该是用的ionic提供的router，我当时之所以放弃这个功能，也是因为两者之间的切换不够smooth，在数据量少的情况下是没有问题，但list里的东西约多，约后面的文章打开也就回约卡，所以我用了ionic提供的modal来代替这个功能，很好的解决了问题。

ionic提供了一个infinite scroll 确实是一个很赞的功能，实现了下拉刷新，向上自动加载。但是，也是同样的问题，内容多了，会卡，我看他是用translate整个list来实现的，我最终也放弃了这个功能。

ionic实现了slide menus和slide box 但是有一个很实用的slide tabs没有提供出来，硬伤，有一个库叫 https://github.com/saravmajestic/ionic/tree/master/tabbedSlideBox
可以实现这个功能，但是用着也不是太爽。

然后其他都是一些不太影响性能的小问题，不做赘述。

**Comment by phodal** [comment]
@sunbirds 谢谢了哈，先保留着这个issue

**Comment by phodal** [comment]
@ sunbirds 大赞一个，刚把文章改为modal，果然流畅了非常多。
