### ISSUE TITLE
iOS客户端文章非代码处出现HTML标签

### ISSUE THREAD

**Issue by kngxscn** [phodal/growth-ionic#41]
例如，《无处不在的HTML》中出现 `<strong>`,`<blockquote>`标签

**Comment by phodal** [comment]
+1

**Comment by kngxscn** [comment]
如果将 growth/www/assets/article/html.md 中的 `<blockquote>`标签 替换为 Markdown 语法中的引用符号`>`，`<strong>`标签替换为 Markdown 语法中的加粗符号`**`，不知道会不会解决这个问题

**Comment by phodal** [comment]
@renzongxian 应该是会解决这个问题的。

**Comment by phodal** [comment]
fixed #42
