### ISSUE TITLE
学习路线 打不开

### ISSUE THREAD

**Issue by ding102992** [phodal/growth-ionic#47]
打印出如下警告：

08-01 11:57:32.783 8117-8117/ren.growth I/chromium: [INFO:CONSOLE(49080)] "WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).", source: file:///android_asset/www/build/js/app.bundle.js (49080)
08-01 11:57:32.784 8117-8117/ren.growth I/chromium: [INFO:CONSOLE(49080)] "WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).", source: file:///android_asset/www/build/js/app.bundle.js (49080)
08-01 11:57:32.784 8117-8117/ren.growth I/chromium: [INFO:CONSOLE(49080)] "WARNING: sanitizing HTML stripped some content (see http://g.co/ng/security#xss).", source: file:///android_asset/www/build/js/app.bundle.js (49080)

**Comment by phodal** [comment]
@ding102992 刚改API的时候出了个错哈，已经修复
