### ISSUE TITLE
Android版图标设计问题

### ISSUE THREAD

**Issue by yodahuang** [phodal/growth-ionic#51]
Growth的图标大小有些略大，在启动器中看来有些突兀（直角矩形的设计也很少见到）
这里是Google的[图标设计指南](https://material.google.com/style/icons.html#icons-product-icons)
一个直观的对比是同样是正方形图标的[Google Map](https://play.google.com/store/apps/detailsid=com.google.android.apps.maps)的图标大小。
当然，如若条件允许，非矩形而是不规则形状的图标自然是更好,这个可以日后优化。

**Comment by phodal** [comment]
收到哈~，谢谢了
