### ISSUE TITLE
miui 8.1 安卓 6.0.1 无法安装

### ISSUE THREAD

**Issue by taoyantu** [phodal/growth-ionic#56]
您好，我的手机是 miui 8.1 安卓 6.0.1 ，无法安装成功，很喜欢您这个APK ，能否帮忙看一下。谢谢

**Comment by phodal** [comment]
@taoyantu 我这里没有 MIUI 的手机，要复现这个 Bug 可能有些难度。一般来说安装不了，可能是证书的问题，或者 网络错误 。

最好可以提供一下手机的信息，如机型

**Comment by taoyantu** [comment]
小米 Max 4g 128g 版本。

**Comment by taoyantu** [comment]
从 play商店下载了，可以用了。谢谢
