### ISSUE TITLE
Growth专业版技能树滑动问题

### ISSUE THREAD

**Issue by imxfly** [phodal/growth-ionic#57]
- 滑动问题
往右划不动，往左滑动只会拉出Drawer Layout，不能对树进行左滑操作
- 建议
    1. 左滑不要触发左侧边栏，点击左上角三条杠触发即可
    2. 对树的滑动不灵活，需要改进一下
    3. 可以搞成放大缩小的功能，方便全局观看

**Comment by phodal** [comment]
+1

**Comment by CXOldStar** [comment]
+1
而且我的手机屏幕显示不了最下面那一栏,可以左右滑动但是不能上下滑动!?

**Comment by phodal** [comment]
@CXOldStar图片应该可以缩放的吧

**Comment by phodal** [comment]
关闭 ~。原因：交由 React Native 实现的 Growth 3.0 项目 https://github.com/phodal/growth
