### ISSUE TITLE
安卓7.1下 Google Play 版客户端查看在线阅读时显示undefined

### ISSUE THREAD

**Issue by AkariMarisa** [phodal/growth-ionic#59]
本人在Google play市场上下载的客户端，使用时没有登录用户，点击探索栏目下的全栈增长工程师实战下的序章时，页面提示undefined，望处理

**Comment by phodal** [comment]
@AkariMarisa 可以发个截图么？电子书发在 Coding 上的，会不会是网站问题。

**Comment by AkariMarisa** [comment]
截图在附件里，貌似打开其他章节，首先会出现undefined，然后才显示内容2017年2月25日 14:47，Phodal Huang <notifications@github.com>写道：@AkariMarisa 可以发个截图么？电子书发在 Coding 上的，会不会是网站问题。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




2017年2月25日 14:47，Phodal Huang <notifications@github.com>写道：@AkariMarisa 可以发个截图么？电子书发在 Coding 上的，会不会是网站问题。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




2017年2月25日 14:47，Phodal Huang <notifications@github.com>写道：@AkariMarisa 可以发个截图么？电子书发在 Coding 上的，会不会是网站问题。

**Comment by phodal** [comment]
@AkariMarisa 这应该是个 Bug

**Comment by phodal** [comment]
关闭 ~。原因：交由 React Native 实现的 Growth 3.0 项目 https://github.com/phodal/growth
