### ISSUE TITLE
发现一处笔误

### ISSUE THREAD

**Issue by ethanyu336** [phodal/growth-ionic#63]
![2017-03-23-111648_1366x768_scrot](https://cloud.githubusercontent.com/assets/16498050/24230475/4bbf0434-0fba-11e7-884e-5c70c263f2b1.png)

谢谢up主写的书，很循循善诱

这里是story，应该是store吧

**Comment by phodal** [comment]
@YuSuu 欢迎来 pr 哈

**Comment by ethanyu336** [comment]
呃，不太会诶，我琢磨琢磨

**Comment by phodal** [comment]
已经移动 https://github.com/phodal/growth-ebook/issues/66 中了哈，不是这个 Repo 里的内容
