### ISSUE TITLE
代码块无法滑动问题

### ISSUE THREAD

**Issue by Nicolas-Lsy** [phodal/growth-ionic#64]
全栈增长工程师 （序言一章undefined）一文
 代码块全都无法左右滑动观看， 其他文章可以呀；是不是更新版本没修复？

**Comment by snowden-fu** [comment]
iOS版本滑动可以后退，但是按钮后退不行

**Comment by phodal** [comment]
@snowdenfu get

**Comment by phodal** [comment]
关闭 ~。原因：交由 React Native 实现的 Growth 3.0 项目 https://github.com/phodal/growth
