### ISSUE TITLE
Insight - Todo里的项目无法取消和重新选择

### ISSUE THREAD

**Issue by keithmork** [phodal/growth-ionic#66]
Android7.1.2

取消勾选后还留在已完成里，不会移上去
之后没法重新再勾，选了之后返回再进，还是未勾上的状态

**Comment by phodal** [comment]
@keithmork 版本是 2.5.0？

**Comment by keithmork** [comment]
是的 2.5.0
google play上下的

PS：wlgq，我们同城 ：）

**Comment by phodal** [comment]
关闭 ~。原因：交由 React Native 实现的 Growth 3.0 项目 https://github.com/phodal/growth
