### ISSUE TITLE
后端的python代码是否有开源?

### ISSUE THREAD

**Issue by shenguanjiejie** [phodal/growth-ionic#67]
你好 我最近初学python 很想找一个写app后端的python项目看一看 但是我clone了growth,发现只有两个py文件,请问python部分代码只有这些么?请告知 感激不尽 谢谢

**Comment by phodal** [comment]
可以看 [全栈增长工程师实战](https://github.com/phodal/growth-in-action) 这本书啊~，或者等 Growth 的纸质版《全栈应用开发：精益实践》出版

**Comment by shenguanjiejie** [comment]
嗯嗯 谢谢 不过我看这里都是一些指导和代码片段 看不到整个流程和细节 感觉看了后还是不能直接写app后端...
